In [29]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle

In [30]:
## load the ANN trained model , scalar pickle , onehot
model = load_model('model.h5')

## load the label and onehot pickle file.
with open('label_encoder_gender.pkl' , 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('onehot_encoder_geo.pkl' , 'rb') as file :
    onehot_encoder_geo = pickle.load(file)

## load the scalar pickle file.
with open('scalar.pkl' , 'rb') as file:
    scalar = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [31]:
# Example input data
input_data = {
    "CreditScore" : 600 , 
    "Geography" : 'France' ,
    "Gender" : 'Male' ,
    'Age' : 48 ,
    "Tenure" : 3 ,
    "Balance" : 500000 ,
    "NumOfProducts": 2 , 
    "HasCrCard": 1 ,
    "IsActiveMember": 1 ,
    "EstimatedSalary": 10000 
}

In [32]:
input_df = pd.DataFrame([input_data])

In [ ]:
# Ome Hot Encoding on "Geography"
geo_encoded = onehot_encoder_geo.transform(input_df[['Geography']])
geo_encoded_df = pd.DataFrame(geo_encoded , columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [40]:
# Label Encoding on "Gender"
input_df['Gender'] = label_encoder_gender.transform(input_df[['Gender']])

d:\AI\Projects\DL Projects\Customer Churn Prediction\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [41]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,48,3,500000,2,1,1,10000,1.0,0.0,0.0

In [34]:
input_df = input_df.drop('Geography', axis=1)

In [35]:
input_df = pd.concat([input_df.reset_index(drop=True),
                      geo_encoded_df.reset_index(drop=True)], axis=1)

In [36]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,48,3,500000,2,1,1,10000,1.0,0.0,0.0

In [42]:
# Scalling the input data
input_scaled = scalar.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.86537308, -0.69539349,  6.78702418,
         0.80843615,  0.64920267,  0.97481699, -1.57229902,  1.00150113,
        -0.57946723, -0.57638802]])

In [44]:
# Predict Churn
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step

array([[0.82843745]], dtype=float32)

In [47]:
prediction_prob = prediction[0][0]

In [51]:
prediction[0][0]

np.float32(0.82843745)

In [49]:
if prediction_prob < 0.5:
    print("Customer is likely to Churn.")
else: 
    print('Customer is not likely to Churn')

Customer is not likely to Churn